[package]
name = "card_deck"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"

[lib]
name = "card_deck"
path = "src/lib.rs"
crate-type = ["lib"]
